kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: ci-pipeline-scc
allowPrivilegedContainer: true
defaultAddCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:continuous-infra:jenkins
groups:
