apiVersion: v1
kind: BuildConfig
metadata:
  name: build-containers
  namespace: continuous-infra
  selfLink: /oapi/v1/namespaces/continuous-infra/buildconfigs/build-containers
  uid: 21313ff3-6d60-11e7-88b8-1636d829280f
  resourceVersion: '38238'
  creationTimestamp: '2017-07-20T15:28:49Z'
  labels:
    app: jenkins-pipeline-example
  annotations:
spec:
  triggers:
    - type: GitHub
      github:
        secret: secret101
    - type: Generic
      generic:
        secret: secret101
  runPolicy: Serial
  source:
    type: None
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node() {
          stage('build') {
            openshiftBuild(buildConfig: 'rpmbuild', showBuildLogs: 'true')
            openshiftBuild(buildConfig: 'ostree', showBuildLogs: 'true')
            openshiftBuild(buildConfig: 'e2e', showBuildLogs: 'true')
          }
        }
  output: {}
  resources: {}
  postCommit: {}
  nodeSelector: null
status:
  lastVersion: 3

