---
# clone the pipeline repo

# git clone
- name: "checkout the pipeline @ {{ pipeline_repo }} to {{ pipeline_dir }}"
  git:
    repo: "{{ pipeline_repo }}"
    dest: "{{ pipeline_dir }}"
    version: "{{ pipeline_branch }}"
    refspec: "{{ pipeline_refspec }}"
    force: yes
